defaults:
  - _self_
pretrained: imagenet
instance:
  _target_: models.ResNet_distilbert_lora.ResNetDistilBert
  num_channels: 47
  head_hidden_dim: 256
  head_dropout: 0.15
  ch_emb_dim: 16
  year_proj_dim: 8
  date_proj_dim: 16
  cy_hidden: 16

name: RESNET_DISTILBERT_LORA