defaults:
  - _self_
pretrained: webli
instance:
  _target_: models.siglip_unfrozen.SigLIPRegressor
  frozen: True

  # progressive-unfreeze parameters
  unfreeze_enable: true
  unfreeze_epoch_fraction: ${unfreeze_fraction}   
  total_epochs: ${epochs}      
  unfreeze_top_blocks: 2          # unfreeze 2 ↑,2 ↓ blocks
  unfreeze_proj: true

  add_year_proj: true
  year_proj_dim: 8

name: SIGLIP