defaults:
    - val_transform: siglip
    - train_transform: siglip
accum_steps: 1
batch_size: 64
num_workers: 16
metadata: ["title", "year_norm", "year_idx", "channel_idx", "date_sin","summary"] #
val_ratio: 0.1 
seed: 42
train_on_log: false
augmentation: true
