_target_: torch.optim.AdamW
lr_body: 2e-6      # lent
lr_head: 5e-5
lr_image_adapter: 2e-6    # only image‐LoRA
lr_text_adapter: 2e-6    # only text‐LoRA (title+summary)
#lr_head: 5e-5    # head MLP, year/date/channel embeds, etc.
lr_fusion: 5e-5    # fusion transformer or simple_fusion MLP


weight_decay: 0.01
betas: [0.9, 0.999]