_target_: torch.optim.AdamW
<<<<<<< HEAD
head_lr: ${if:${dataset.train_on_log}, 2e-4, 4e-3}       # rapide
body_lr: ${if:${dataset.train_on_log}, 2e-6, 2e-5}        # lent
weight_decay: 0.01
=======
head_lr: 10e-3       # rapide
body_lr: 5e-5        # lent
weight_decay: 0.005
>>>>>>> 27a24ec (planification)
betas: [0.9, 0.999]